- CHANGELOG.md
- Dockerfile
- docker-compose.yml
- tutum.yml
> Bump to Citus v5.0.1, use PGDG package

- README.md
- docker-compose.yml
To test the newest configuration image as well.
> Flip Docker Compose to a nightly for now

- README.md
> update postgres version in readme

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
Changes to bump Citus to version 6.2.2
> Release 6.2.2

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
Changes to bump Citus to version 6.2.2
> Bump Citus to 6.2.2

- Dockerfile-alpine
For a smaller, more nimble Citus.
If this proves useful, I can look into adding a nightly eventually as well.
Fixes #19.
> Add Alpine image variant

- Dockerfile
- Dockerfile-alpine
Ran into a bit of trouble with Debian Stretch changes.
Everything works well now; need to merge install script updates first.
> Update main/alpine Dockerfile for PG 10

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
Bump citus,hll and topn versions, also upgrade PG to 11.
> Release 8.0.0 and Update PG to 11

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
Bump citus,hll and topn versions, also upgrade PG to 11
> Bump docker to 8.0.0 and PG 11

- .travis.yml
- CHANGELOG.md
- Dockerfile
- docker-compose.yml
> Bump to 8.0.0.1

- .travis.yml
- CHANGELOG.md
- Dockerfile
- docker-compose.yml
> Bump image to 8.0.0-1

- docker-compose.yml
Since we don't have 8.0.0-1 as tag use 8.0.0 in docker compose
> Use 8.0.0 as tag

- docker-compose.yml
Since we don't have 8.0.0-1 as tag use 8.0.0 in docker compose
> Use 8.0.0 as tag in docker compose

- .travis.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile-alpine
- docker-compose.yml
Rollback PostgreSQL version to 12.1 (see issue #170)
> Bump docker to 9.2.2-1 & rollback PostgreSQL version to 12.1

- Dockerfile-alpine
Missed a copy paste to the alpine Dockerfile
> Do same PGPASSWORD fix for alpine images

- docker-compose.yml
https://github.com/citusdata/membership-manager/issues/10#issuecomment-653657806
> Fix manager crash in rootless docker

- citus_10_pg_12_5.dockerfile
> add dockerfile for citus 10.0.2 on postgres 12.5

- .github/workflows/publish_docker_images_cron.yml
- .github/workflows/publish_docker_images_on_manual.yml
- .github/workflows/publish_docker_images_on_push.yml
Fixes issues for citusdata/tools#140
> Fixes readability,standardization and security issues for pipeline files

- .github/workflows/publish_docker_images_on_push.yml
This PR is releated to https://github.com/citusdata/tools/pull/184. Need to change the tag with branch name to test it. After closing  tools PR I need to replace the branch name with tag
> Fixes pipeline trigger problem on tagging

- .github/workflows/publish_docker_images_on_tag.yml
I tested on gurkanindibay/docker repo since test is required on master branch
https://github.com/gurkanindibay/docker/runs/5247869072?check_suite_focus=true
> Adds docker publish pipeline with tag trigger

- Dockerfile
- alpine/Dockerfile
- postgres-12/Dockerfile
- postgres-13/Dockerfile
Additionally, fixed Alpine build problem because of missing library after upgrade
> Updates postgres versions for images

- docker-compose.yml
Need to reflect this in our update_docker.py script as well. (cc: @gurkanindibay)
> Use correct version for beta release

- CHANGELOG.md
- Dockerfile
- alpine/Dockerfile
- docker-compose.yml
- postgres-12/Dockerfile
- postgres-13/Dockerfile
Adds additional dependencies for pg_send_cancellation build (libxslt linxml2)
> Bump docker to version 11.0.2

- .github/workflows/publish_docker_images_cron.yml
- .github/workflows/publish_docker_images_on_manual.yml
- .github/workflows/publish_docker_images_on_push.yml
- .github/workflows/publish_docker_images_on_tag.yml
- .github/workflows/update_version.yml
Now nightlies getting error since v0.8.20 python requirements execution fails. This PR updates tools into v0.8.24
> Updates tools into v0.8.24

- Dockerfile
- alpine/Dockerfile
- postgres-13/Dockerfile
- postgres-14/Dockerfile
Updates Postgres versions
15.1=>15.2
14.6=>14.7
13.9=>12.10
> Updates postgres versions into latest
